# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amqcli < Formula
  desc "ActiveMQ TUI Client - Manage and monitor ActiveMQ queues and messages via terminal"
  homepage "https://github.com/xvlet/amqcli"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.2/amqcli_darwin_amd64.tar.gz"
      sha256 "b2f7ea0edbf4773a4c59672a9b3b6199c3711aa822faa07a873c1ee937c92c2b"

      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.2/amqcli_darwin_arm64.tar.gz"
      sha256 "623f9847799d3488aecc59dcb1ef46b1bfa64e73ca98eff099cfd081514aae0c"

      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.2/amqcli_linux_amd64.tar.gz"
      sha256 "fe73361b6da8cc636ae73360c7f937b8c79c32f37a12b193817d4989ab632eba"
      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.2/amqcli_linux_arm64.tar.gz"
      sha256 "13fd3666c58ff973655d24fdd8ba05ac837e4a249b2b10be276579f207d03599"
      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
  end

  test do
    system "#{bin}/amqcli", "--version"
  end
end
