# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amqcli < Formula
  desc "ActiveMQ TUI Client - Manage and monitor ActiveMQ queues and messages via terminal"
  homepage "https://github.com/xvlet/amqcli"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.1/amqcli_darwin_amd64.tar.gz"
      sha256 "cef963ec4847d3196750c8380b934778dfd336fd8a3e0406aaf4312f9272c029"

      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.1/amqcli_darwin_arm64.tar.gz"
      sha256 "8e386a69417ff66f5dd9e037475ffe68e84a9ea6c807f501011c2e3c353ce01e"

      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.1/amqcli_linux_amd64.tar.gz"
      sha256 "55ae8127e897f6c9e005e4722b329a9c1a1386c40b35d0f20fc79bc73e76e0e6"
      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.1/amqcli_linux_arm64.tar.gz"
      sha256 "0e152fd31f094212102ed78a6ad3a661fd1670cdd44686388dfe1b3289fd1fe1"
      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
  end

  test do
    system "#{bin}/amqcli", "--version"
  end
end
