# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amqcli < Formula
  desc "ActiveMQ TUI Client - Manage and monitor ActiveMQ queues and messages via terminal"
  homepage "https://github.com/xvlet/amqcli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.0/amqcli_darwin_amd64.tar.gz"
      sha256 "a4c3b838a9c066383f183c9a9c75264b975240a6824435dffc5e3133a1610b9a"

      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.0/amqcli_darwin_arm64.tar.gz"
      sha256 "7056f73a35e2f438c0166974dcc2c512ef46aed4531eb11477f698a49b366942"

      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.0/amqcli_linux_amd64.tar.gz"
      sha256 "ade552a34a98d790aa05dc32feb07e75a2637c55112305bcd2cded17a34a3178"
      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/xvlet/amqcli/releases/download/v0.1.0/amqcli_linux_arm64.tar.gz"
      sha256 "2463a8d8369df9c06abca8c973dbea0cbef8577de8dc3684439adab07e266182"
      define_method(:install) do
        bin.install "amqcli"
        (etc/"amqcli").install "config.yml"
      end
    end
  end

  test do
    system "#{bin}/amqcli", "--version"
  end
end
